config/routes.rb
Rails.application.routes.draw do
    devise_for :users, path_prefix: 'my', controllers: { registrations: 'registrations',
        omniauth_callbacks: 'callbacks' }
    resources :users, only: [:index, :show]
    get '/projects/lang', to: 'projects#show_lang'
    resources :projects do
        resources :comments, only: [:index, :new, :create, :destroy]
    end
    resources :comments, only: [:index]
    root 'users#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :commenter
    belongs_to :project
end

app/models/commenter.rb
class Commenter < ApplicationRecord
    belongs_to :user
    has_many :comments
    has_many :projects, through: :comments
end

app/models/project.rb
class Project < ApplicationRecord
    belongs_to :user
    has_many :comments
    has_many :commenters, through: :comments
    # scope :imported,    -> { where(imported: true) }
    scope :get_lang,   ->(lang) { where("language = ?", lang) }

    validates :name, presence: true

    def self.get_uniq_langs
        Project.all.collect{ |p| p.language }.uniq
    end

    def self.relate_to_record(array)
        array.collect { |proj| Project.find_by(id: proj.id) }
    end

end

app/models/user.rb
class User < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable, :trackable
    devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable,
    :omniauthable

    validates :name, presence: true


    # relationships
    has_many :projects
    has_one :commenter
    has_many :comments, through: :commenter

    # instance methods
    def get_projects_from_github
        if self.provider == "github"
            @response = Excon.get(self.github_repos)
        end

        return nil if @response.status != 200

        JSON.parse(@response.body)
    end

    # class methods
    def self.from_omniauth(auth)
        where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
            user.provider = auth.provider
            user.name = auth.info.name
            user.uid = auth.uid
            user.email = auth.info.email
            user.github_repos = auth.extra.raw_info.repos_url
            user.password = Devise.friendly_token[0,20]
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    private

    def after_sign_out_path_for(resource_or_scope)
        root_path
    end
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
    def github
        @user = User.from_omniauth(request.env["omniauth.auth"])
        if @user.commenter.nil?
            @user.create_commenter
        end
        sign_in_and_redirect @user
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def index
        if params[:project_id]
            @project = Project.find_by(id: params[:project_id])
            @comments = @project.comments
            # redirect_to projects_path, if @project.nil?
        else
            @comments = Comment.all
        end
    end

    def new
        if params[:project_id]
            @project = Project.find_by(id: params[:project_id])
            @comment = @project.comments.new
        end
    end

    def create
        @commenter = Commenter.find_by(id: params[:comment][:commenter_id])
        @project = Project.find_by(id: params[:comment][:project_id])
        if !params[:comment][:content].empty?
            @commenter.comments.create(comment_params)
        end
        redirect_to project_path(@project)
    end

    def destroy

    end

    private

    def comment_params
        params.require(:comment).permit(:commenter_id, :content, :project_id)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_action :set_project, only: [:show, :edit, :update, :destroy]

    def index
        @projects = Project.all
    end

    def show_lang
        # binding.pry
        projects_array = Project.get_lang(params[:project][:language])
        @projects = Project.relate_to_record(projects_array)
        render 'projects/index.html.erb'
    end

    def new
        @project = Project.new(user_id: current_user)
    end

    def create
        @project = current_user.projects.build(new_project_params(:user_id, :name, :language, :description, :url))
        if @project.save
            redirect_to project_path(@project)
        else
            render :new
        end
    end

    def show

    end

    def edit

    end

    def update
        if @project.update(update_project_params)
            redirect_to project_path(@project)
        else
            render :edit
        end
    end

    def destroy
        @project.destroy
        redirect_to user_path(current_user)
    end


    private

    def set_project
        @project = Project.find_by(id: params[:id])
        redirect_to projects_path, alert: "Project not found." if @project.nil?
    end

    def new_project_params(*args)
        params.require(:project).permit(*args)
    end

    def update_project_params
        params.require(:project).permit(:name,
                                        :url,
                                        :language,
                                        :description)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    def create
        super
        if resource.persisted?
            resource.create_commenter
        end
    end

    private

    def sign_up_params
        params.require(:user).permit(   :name,
                                        :email,
                                        :password,
                                        :password_confirmation)
    end

    def account_update_params
        params.require(:user).permit(   :name,
                                        :email,
                                        :password,
                                        :password_confirmation,
                                        :current_password)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :get_user, only: :show

    def index
        @users = User.all
    end

    def show
    end


    private

    def get_user
        @user = User.find_by(id: params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
    def edit_project(proj)
        if user_signed_in?
            if proj.user_id == current_user.id
                link_to('Edit', edit_project_path(proj))
            end
        end
    end

    def deleteable?(proj)
        if current_user == proj.user
            button_to("Delete", project_path(proj), method: :delete)
        end
    end
end

app/helpers/users_helper.rb
module UsersHelper
    def github?(user)
        user.provider == "github"
    end
end

app/views/comments/_comments.html.erb
<% comments.each do |comm| %>
    <div class="comment">
        <h5><%= comm.commenter.user.name %> said:</h5>
        <p><%= comm.content %></p>
    </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_for (project_comments_path(@project.comments.new)) do |f| %>
    <%= f.hidden_field :commenter_id, value: current_user.commenter.id %>
    <%= f.hidden_field :project_id, value: params[:id] %>
    <%= f.text_area :content %>
    <%= f.submit 'Post Comment' %>
<% end %>

app/views/comments/index.html.erb
<%= render partial: "comments/comments", locals: {comments: @comments} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Code_Is_Life</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        <a class="navbar-brand" href="<%= root_url %>"/>Home</a>
        <a href="<%= projects_path %>">Projects</a>
        <% if user_signed_in? %>
            <a href="<%= user_path(current_user) %>"><%= current_user.name %>'s Profile</a>
            <%= link_to('Log Out', destroy_user_session_path, method: :delete) %>
        <% else %>
            <%= link_to 'Sign Up', new_user_registration_path %>
            <%= link_to 'Log In', new_user_session_path %>
        <% end %>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <!-- content -->
    <div class="container"  role="main">
      <%= yield %>
    </div>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
    <%= f.hidden_field :user_id %>
    <%= f.label :name %>
    <%= f.text_field :name %><br>

    <%= f.label :language %>
    <%= f.text_field :language %><br>

    <%= f.label :description %>
    <%= f.text_field :description %><br>

    <%= f.label :url %>
    <%= f.text_field :url %><br>

    <%# if current_user.provider == "github" %>
        <%# select("project", "imported", options_for_select(@github_projects.collect {|proj| [proj[:name], proj[:github_id]] }), { include_blank: true }) %>
    <%# end %>

    <%= f.submit %>
<% end %>

app/views/projects/_projects.html.erb
<table>
    <tr>
        <th>Name</th>
        <th>Language</th>
        <th>Description</th>
        <th></th>
    </tr>
    <% projects.each do |proj| %>
        <tr>
            <td><%= proj.name %></td>
            <td><%= proj.language %></td>
            <td><%= proj.description %></td>
            <td><%= edit_project(proj) %> <%= link_to('View', project_path(proj)) %></td>
        </tr>
    <% end %>
</table>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<% if @project.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@project.errors.count, "error") %>
      prohibited this project from being saved:
    </h2>

    <ul>
    <% @project.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= render 'form' %>

app/views/projects/index.html.erb
<%# <%= link_to 'Ruby only projects', projects_ruby_path %>
<%= form_with(url: projects_lang_path, method: "get") do %>
    <%= select("project", "language", Project.get_uniq_langs.collect { |lang| [lang, lang] } ) %>
    <%= submit_tag "Submit" %>
<% end %>
<%= render partial: "projects/projects", locals: {projects: @projects} %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<% if @project.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@project.errors.count, "error") %>
      prohibited this project from being saved:
    </h2>

    <ul>
    <% @project.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<h4>Create a new Project.</h4>

<%= render 'form' %>

app/views/projects/new_with_github.html.erb
<h1>New Project</h1>

<h4>Create a new Project or Import one from Github.</h4>

<%= render 'form' %>

app/views/projects/show.html.erb
<h1><%= @project.name %></h1>
<h3>By: <%= @project.user.name %></h3>

<p>Written in: <%= @project.language %></p>
<p>Repo URL: <%= link_to @project.url %></p>

<%= deleteable?(@project) %>

<p><%= @project.description %></p>

<%= link_to 'Comments on this project', project_comments_path(@project) %>
<%#= render partial: "comments/form" %>

<%= form_for ([@project, @project.comments.new]) do |f| %>
    <%= f.hidden_field :commenter_id, value: current_user.commenter.id %>
    <%= f.hidden_field :project_id, value: params[:id] %>
    <%= f.text_area :content %>
    <%= f.submit 'Post Comment' %>
<% end %>

app/views/users/index.html.erb
<% @users.each do |user| %>
    <%= link_to user.name, user_path(user) %>
<% end %>

app/views/users/show.html.erb
<h1>Welcome to <%= @user.name %>'s Projects</h1>

<%= render partial: "projects/projects", locals: {projects: @user.projects} %>

<% if @user == current_user %>
    <%= link_to 'New Project', new_project_path %>
<% end %>